# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Vlasov.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(727, 339)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(30, 30, 551, 211))
        self.tableWidget.setRowCount(6)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(190, 260, 141, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.tableWidget.setHorizontalHeaderLabels(["ФИО", "Отдел", "Кол-во рабочих дней", "Зарплата"])

        self.tableWidget.setColumnWidth(2, 130)
        self.tableWidget.setColumnWidth(0, 200)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.pushButton.clicked.connect(self.load_data)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Загрузить данные"))

    def load_data(self):
        """Загружает данные из файла salary.txt в таблицу."""
        with open("salary.txt", "r", encoding='utf-8') as file:
            data = file.readlines()

        # Очищаем таблицу
        self.tableWidget.setRowCount(0)

        # Добавляем данные в таблицу
        for row, line in enumerate(data):
            # Разделяем строку на элементы
            elements = line.strip().split(",")
            self.tableWidget.insertRow(row)

            # Вставляем элементы в столбцы
            for col, element in enumerate(elements):
                self.tableWidget.setItem(row, col, QtWidgets.QTableWidgetItem(element))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())